import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Redux/Provider";
// import { useSelector } from "react-redux";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-Auth",
  description: "Generated by Sagar Yenkure",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const dark : boolean = useSelector((state: any) => state.dark_reducer.Darkmode);
  return (
      <html lang="en" >
        <body className={inter.className}>
          <Providers>
          {children}
          </Providers>
          </body>
      </html>
  );
}
